class AppWords {
  static const List<Map<String, String>> quotes = [
    {"author": "Cemil Meriç", "quote": "Okumak, ruhu inceltir."},
    {"author": "Cicero", "quote": "Kitaplar, sessiz öğretmenlerdir."},
    {"author": "Victor Hugo", "quote": "Bir kitap, yeni bir hayattır."},
    {"author": "Umberto Eco", "quote": "Okuyan insan, iki hayat yaşar."},
    {"author": "William Shakespeare", "quote": "Kitaplar, düşüncenin kanatlarıdır."},
    {"author": "Jean-Paul Sartre", "quote": "Okumak, özgürlüğün anahtarıdır."},
    {"author": "Ernest Hemingway", "quote": "Kitaplar, en sadık dostlardır."},
    {"author": "George R. R. Martin", "quote": "Okumayan insan, tek bir hayat yaşar."},
    {"author": "Sabahattin Ali", "quote": "Kitaplar, insanı insana anlatır."},
    {"author": "René Descartes", "quote": "Okumak, düşünmenin en güzel yoludur."},
    {"author": "Seneca", "quote": "Kitaplar, aklın gıdasıdır."},
    {"author": "Jules Verne", "quote": "Okumak, hayal kurmayı öğretir."},
    {"author": "Dostoyevski", "quote": "Kitap, insanın iç yolculuğudur."},
    {"author": "Franz Kafka", "quote": "Okumak, insanı derinleştirir."},
    {"author": "Marcel Proust", "quote": "Kitaplar, yalnızlığı dostluğa çevirir."},
    {"author": "Goethe", "quote": "Okumak, ruhun aynasıdır."},
    {"author": "Jorge Luis Borges", "quote": "Kitaplar, zamanı durdurur."},
    {"author": "Albert Camus", "quote": "Okumak, kendini keşfetmektir."},
    {"author": "Orhan Pamuk", "quote": "Kitap, düşüncenin evidir."},
    {"author": "Voltaire", "quote": "Okumak, insanı özgürleştirir."},
    {"author": "Nazım Hikmet", "quote": "Kitaplar, sessiz devrimlerdir."},
    {"author": "Tolstoy", "quote": "Okumak, hayatı anlamaktır."},
    {"author": "Halide Edib Adıvar", "quote": "Kitaplar, insanın ufkunu açar."},
    {"author": "Stefan Zweig", "quote": "Okumak, insanı büyütür."},
    {"author": "Platon", "quote": "Kitaplar, düşünceyi besler."},
    {"author": "Paulo Coelho", "quote": "Okumak, bir yolculuktur."},
    {"author": "Aristoteles", "quote": "Kitaplar, ruhun ilacıdır."},
    {"author": "Mark Twain", "quote": "Okumak, dünyayı genişletir."},
    {"author": "İbn Sina", "quote": "Kitaplar, sessiz rehberlerdir."},
    {"author": "Virginia Woolf", "quote": "Okumak, zihni özgür bırakır."},
    {"author": "Konfüçyüs", "quote": "Kitaplar, insanın en iyi öğretmenidir."},
    {"author": "Michel de Montaigne", "quote": "Okumak, düşünceyi derinleştirir."},
    {"author": "Italo Calvino", "quote": "Kitaplar, hayatı çoğaltır."},
    {"author": "Immanuel Kant", "quote": "Okumak, aklı aydınlatır."},
    {"author": "C. S. Lewis", "quote": "Kitaplar, hayal gücünü büyütür."},
    {"author": "Ralph Waldo Emerson", "quote": "Okumak, ruhu besler."},
    {"author": "Charles Dickens", "quote": "Kitaplar, sessiz dostlardır."},
    {"author": "Friedrich Nietzsche", "quote": "Okumak, insanı özgün kılar."},
    {"author": "Haruki Murakami", "quote": "Kitaplar, zamanı aşar."},
    {"author": "Ahmet Hamdi Tanpınar", "quote": "Okumak, hayatı güzelleştirir."}
  ];
}
